Repository FRONTENDBOOTCAMP-14th/HOT6, pull requests merged in 2025-07, with the labels that each got.

#9 Feat/profile card component/jung
  src/components/profile-card.css
  src/components/profile-card.html
  vite.config.js
Labels: feature

#12 Feat/card components/kim
  src/assets/styles/common/theme.css
  src/components/card/card.css
  src/components/card/card.html
  src/main.css
Labels: feature

#18 Feat/main/kim - 버튼 컴포넌트 파일 수정(html, css)
  src/components/button/button.css
  src/components/button/button.html
Labels: feature

#19 Feat/header/jung
  src/components/header/header.css
  src/components/header/header.html
  src/components/navigation-bar/navigation-bar.css
  src/components/searchbar/searchbar.css
Labels: feature

#23 [Feat] 도서 상세페이지 모달 마크업 및 스타일링
  index.html
  src/components/book-modal/book-modal.css
  src/components/book-modal/book-modal.html
Labels: feature

#26 Feat/about page/jung
  src/components/navigation-bar/navigation-bar.css
  src/components/profile-card/profile-card.css
  src/pages/about/about-page.css
  src/pages/about/about-page.html
Labels: feature

#30 Feat/favorites/kim
  src/main.css
  src/pages/favorites/favorites.css
  src/pages/favorites/favorites.html
Labels: feature

#31 [Feat] Authors 페이지 마크업 및 스타일링
  src/main.css
  src/pages/author/author.css
  src/pages/author/author.html
Labels: feature

#32 Feat/main/kim
  src/pages/main-page/main-page.css
  src/pages/main-page/main-page.html
  src/pages/main/main.html
Labels: feature

#39 [Fix] 랜딩페이지 레이아웃 깨짐 수정
  src/pages/landing/landing-page.css
Labels: bugfix

#43 Feat/naver api linking/nam
  src/components/book-modal/book-modal.css
  src/main.js
  src/pages/home/home.css
  src/pages/home/home.html
  src/scripts/naver-api.js
  vite.config.js
Labels: feature

#46 [Style] cancel 버튼 숨김 해제
  src/components/searchbar/searchbar.css
  src/main.js
  src/pages/about/about-page.html
  src/pages/author/author.html
  src/pages/favorites/favorites.html
  src/pages/home/home.html
  src/pages/main-page/main-page.html
  src/scripts/clear-button.js
Labels: feature

#47 [Fix] 충돌 해결 과정에서 지우지 못한 마크업 코드 제거
  src/pages/home/home.html
Labels: bugfix

#54 Feat/search books infinite scroll/nam
  src/components/book-modal/book-modal.css
  src/scripts/naver-api.js
Labels: bugfix

#59 [Feat] Favorite 버튼 기능 구현
  src/scripts/naver-api.js
Labels: SOS, feature

#53 Feat/authors page js/park
  src/main.js
  src/pages/author/author.css
  src/pages/author/author.html
  src/scripts/author.js
Labels: feature

#65 Feat/render favorite list/jung
  src/main.js
  src/pages/favorites/favorites.css
  src/pages/favorites/favorites.html
  src/pages/home/home.css
  src/scripts/render-favorite.js
Labels: feature

#67 [Fix] 카드 내 즐겨찾기 상태 변경시 모든 모달에 적용되는 버그 수정
  src/scripts/naver-api.js
Labels: bugfix

#69 [Refactor] 코드 구조 변경, 중복 코드 제거
  src/scripts/author.js
Labels: bugfix
